# check for version information in documentation https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3.3"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 3

  engine:
    build: "./ENGINE"
    depends_on:
      - "rabbitmq"
    command: ["/wait-for-it.sh", "rabbitmq:5432", "--", "npm", "start"]

  # enginemovehandler:
  #   build: "./EngineMoveHandler"
  #   ports:
  #     - "7000:7000"
  #   depends_on:
  #     - "rabbitmq"
  #   command: ["/wait-for-it.sh", "rabbitmq:5432", "--", "npm", "start"]

  # usermovehandler:
  #   build: "./UserMoveHandler"
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - "rabbitmq"
